{
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="JASS"
  psiImplClassSuffix="Impl"

  parserClass=              "guru.xgm.jass.lang.PsiParserJASS"
  psiPackage=               "guru.xgm.jass.psi"
  psiImplPackage=           "guru.xgm.jass.psi.impl"
  elementTypeHolderClass=   "guru.xgm.jass.psi.TypesJASS"
  //psiImplUtilClass=         "guru.xgm.jass.psi.PsiImplUtilJASS"
  elementTypeClass=         "guru.xgm.jass.psi.tree.IElementTypeJASS_Element"
  tokenTypeClass=           "guru.xgm.jass.psi.tree.IElementTypeJASS_Token"
}

script ::= (typeDeclaration|nativeDeclaration|SINGLE_LINE_COMMENT)*

typeDeclaration ::= KEYWORD_TYPE IDENTIFIER KEYWORD_EXTENDS IDENTIFIER SINGLE_LINE_COMMENT*
nativeDeclaration ::= KEYWORD_CONSTANT? KEYWORD_NATIVE IDENTIFIER KEYWORD_TAKES (KEYWORD_NOTHING|variableDeclaration (COMMA variableDeclaration)*) KEYWORD_RETURNS (KEYWORD_NOTHING|IDENTIFIER)
private variableDeclaration ::= IDENTIFIER IDENTIFIER
