// https://github.com/JetBrains/intellij-plugins/blob/master/Dart/src/com/jetbrains/lang/dart/Dart.bnf
{
  parserClass="guru.xgm.jass.lang.PsiParser_JASS"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="JASS_"
  psiImplClassSuffix="Impl"

  psiPackage=               "guru.xgm.jass.psi"
  psiImplPackage=           "guru.xgm.jass.psi.impl"
  elementTypeHolderClass=   "guru.xgm.jass.psi.Types_JASS"
  psiImplUtilClass=         "guru.xgm.jass.psi.PsiImplUtil_JASS"
  elementTypeClass=         "guru.xgm.jass.psi.tree.IElementType_Element_JASS"
  tokenTypeClass=           "guru.xgm.jass.psi.tree.IElementType_Token_JASS"
}

jassFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY {
  mixin="guru.xgm.jass.extapi.psi.ASTWrapperPsiElement_JASS"
  implements="guru.xgm.jass.psi.PsiNameIdentifierOwner_JASS"
  methods=[getKey getValue getName setName getNameIdentifier getPresentation]
}
