// https://github.com/JetBrains/intellij-plugins/blob/master/Dart/src/com/jetbrains/lang/dart/Dart.bnf
{
  parserClass="org.intellij.sdk.language.parser.JassParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Jass"
  psiImplClassSuffix="Impl"
  psiPackage="org.intellij.sdk.language.jass.psi"
  psiImplPackage="org.intellij.sdk.language.jass.psi.impl"

  elementTypeHolderClass="org.intellij.sdk.language.jass.psi.JassTypes"
  elementTypeClass="org.intellij.sdk.language.jass.psi.JassElementType"
  tokenTypeClass="org.intellij.sdk.language.jass.psi.JassTokenType"

  psiImplUtilClass="org.intellij.sdk.language.jass.psi.impl.JassPsiImplUtil"
}

jassFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY
{
  methods=[getKey getValue]
}
