{
    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Wts"
    psiImplClassSuffix="Impl"

    parserClass=              "guru.xgm.language.wts.parser.WtsParser"
    psiPackage=               "guru.xgm.language.wts.psi"
    psiImplPackage=           "guru.xgm.language.wts.psi.impl"
    elementTypeHolderClass=   "guru.xgm.language.wts.psi.WtsTypes"
    elementTypeClass=         "guru.xgm.language.wts.psi.tree.WtsIElement"
    tokenTypeClass=           "guru.xgm.language.wts.psi.tree.WtsIToken"

    generateTokenAccessors=true

    tokens = [
        WHITE_SPACE='regexp:\s+'
        SINGLE_LINE_COMMENT="regexp://[^\n]*"
        ID='regexp:\d+'

        STRING='STRING'
        VALUE="regexp:\{[^}]*}"
    ]
}

Root ::= Item*

Item ::= STRING ID VALUE
